pipeline{
  agent any
  stages{
    stage('build'){
      steps{
        sh '''
        
        echo "Build is running on host `hostname`"
        bash ${WORKSPACE}/linux/scripting/shell/for.sh
        bash ${WORKSPACE}/linux/scripting/shell/fun.sh

        '''
      }
    }
  }
}
